name: Ping Render Service on 3rd Tuesdays

on:
  schedule:
    # This cron expression means:
    # - Minute: */5 (every 5 minutes)
    # - Hour: * (every hour)
    # - Day of Month: 15-21 (days 15 through 21)
    # - Month: * (every month)
    # - Day of Week: 2 (Tuesday)
    # IMPORTANT: GitHub Actions cron schedules run in UTC.
    - cron: '* * * * *'

jobs:
  ping_render:
    name: Ping Render App
    runs-on: ubuntu-latest # Use a standard Linux runner
    steps:
      - name: Send GET request to Render service
        run: |
          # Replace the URL below with your actual Render service endpoint
          curl -sS "https://mbryoboards-backend.onrender.com/api/boards" > /dev/null || echo "Ping to Render app failed at $(date)"
          # -sS: Silent mode, but show errors.
          # > /dev/null: Discard the actual response body (we just want to make the request).
          # || echo ...: If curl fails (e.g., non-0 exit code), print an error message to the Action log.